### ISSUE TITLE
whether run quake.py need a long time?

### ISSUE THREAD

**Issue by tiramisutes** [davek44/Quake#2]
Hi,
I have some question when run quake.py. this is my command:
`quake.py -f Quakefile --int --no_cut --no_count -k 19 -p 10 -q 33`

I have prepared 3 files in the current directory : cutoff.txt(cov_model.py produced), infiles(contains the paths for all the fastq reads)and infiles.cts come from the JELLYFISH kmer counts (dump) for reads in infiles.
But the output as follow for a long time without any resulted or error. 
`Cutoff: 14`
`0 trusted kmers`
`AT% = -nan`
`A.fastq`
Does It need a long time or what has happened? I need your help, Thanks.

**Comment by davek44** [comment]
That cutoff is higher than all of the k-mer counts. I would plot the k-mer count histogram, and make sure it fits the expected shape. Check out my advice here: http://www.cbcb.umd.edu/software/quake/faq.html

**Comment by tiramisutes** [comment]
But my k-mer size was select based on the k~=log(200G)/log(4) as you advise. my genome is estimated  nearly 2Gb. So, I finally choose the -k 19 and this 19 was also used in JELLYFISH count (-m 19). Thanks for your help.

**Comment by davek44** [comment]
I was referring to FAQ #7 How can I diagnose coverage cutoff problems?

Regardless of the genome size, if you don't have sufficient coverage, you won't be able to correct errors.
